import { Bookmark, ShoppingCart } from 'lucide-react'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Furrl',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <div className='max-w-[30rem] mx-auto'>
          <header className='flex h-12 sticky border-b-2 border-gray-100/70 z-50 top-0 bg-white justify-between items-center'>
            <div></div>
            <Link href='/'>
              <h1 className='text-indigo-500 text-2xl font-medium'>Furrl</h1>
            </Link>
            <div className='flex gap-4'>
              <Link href='/wishlist'>
                <Bookmark size={20} />
              </Link>
              <Link href='/cart'>
                <ShoppingCart size={20} />
              </Link>
            </div>
          </header>
          <div>{children}</div>
        </div>
      </body>
    </html>
  )
}
